= ADR-XXX: Titel des ADRs

////
ADRs besitzen eine feste, einzuhaltende Struktur, jedoch muss nicht jeder Abschnitt zwangsläufig ausgefüllt werden.
Vor jedem Abschnitt steht ein Kommentar mit der Form [MUSS], [SOLL] oder [KANN].
Ein [MUSS] ist immer auszufüllen, ein [SOLL] ist wenn möglich auszufüllen, bei [KANN] ist das Ausfüllen freigestellt.
////

// [KANN] (jedes einzelne Feld ist optional)
Status: {vorgeschlagen | abgelehnt | angenommen | deprecated | … | abgelöst durch ADR-0005 <0005-example.adoc>}
Datum: zuletzt aktualisiert {YYYY-MM-DD}
Entscheider: {Wer hat in diesem ADR entschieden?}
Zuarbeit durch: {Wer wurde nach seiner Meinung gefragt zu Faktoren, die Einfluss auf dieses ADR haben? (SMEs usw.). Mit diesen Personen gibt es einen Dialog.}
Zu informieren: {Wer ist Stakeholder bzgl. dieses ADRs und wird informiert? Mit diesen Personen wird nur einseitig kommuniziert.}

// [MUSS]
== Überschrift des Problems/der Lösung

// [MUSS]
=== Kontext und Problembeschreibung
// Hier in sehr wenigen Sätzen das Problem und seinen Kontext beschreiben. Warum ist das Problem architekturrelevant und welche Auswirkungen hat die Entscheidung?

...

// [MUSS]
=== Entscheidungskriterien
// Hier die relevanten Qualitätsziele, Randbedingungen und Risiken aufzählen. Ggf. auch getroffene Annahmen aufführen.

* Qualitätsziel/Randbedingung 1
* Qualitätsziel/Randbedingung 2
* ...

// [MUSS]
=== Betrachtete Optionen
// Hier werden die verschiedenen zur Auswahl stehenden Handlungsoptionen aufgezählt.
// Es stehen hier nur Überschriften. Details können weiter unten im Abschnitt "Vor- und Nachteile der betrachteten Optionen" beschrieben werden.

* Option 1
* Option 2
* ...

// [MUSS]
=== Entscheidung
// Welche Option aus dem vorigen Abschnitt wurde