// src/pages/articles/list/ui/page.tsx
import { ArticleList } from '~/widgets/article-list';

import type { Article } from '~/entities/article';

export function ArticlesListPage() {
  // Mock data - später durch API-Call ersetzen
  const articles: Array<Article> = [
    {
      id: '1',
      articleNumber: 'ART-001',
      name: 'Laptop Pro 15"',
      description: 'Hochleistungs-Laptop mit 15 Zoll Display',
      price: 1299.99,
      purchasePrice: 899.99,
      stock: 12,
      minStock: 5,
      category: 'Elektronik',
      subcategory: 'Laptops',
      status: 'available',
      taxRate: 19,
      unit: 'Stück',
      isDigital: false,
      createdAt: new Date('2024-01-15'),
      tags: ['Business', 'Premium'],
    },
    {
      id: '2',
      articleNumber: 'ART-002',
      name: 'Wireless Mouse',
      description: 'Ergonomische kabellose Maus',
      price: 29.99,
      purchasePrice: 15.99,
      stock: 45,
      minStock: 10,
      category: 'Zubehör',
      subcategory: 'Eingabegeräte',
      status: 'available',
      taxRate: 19,
      unit: 'Stück',
      isDigital: false,
      createdAt: new Date('2024-02-01'),
      tags: ['Wireless', 'Ergonomisch'],
    },
    {
      id: '3',
      articleNumber: 'ART-003',
      name: 'USB-C Hub',
      description: '7-in-1 USB-C Hub mit HDMI',
      price: 49.99,
      purchasePrice: 25.99,
      stock: 23,
      minStock: 15,
      category: 'Zubehör',
      subcategory: 'Adapter',
      status: 'available',
      taxRate: 19,
      unit: 'Stück',
      isDigital: false,
      createdAt: new Date('2024-02-10'),
      tags: ['USB-C', 'Hub'],
    },
    {
      id: '4',
      articleNumber: 'ART-004',
      name: 'Monitor 27" 4K',
      description: '27 Zoll 4K Monitor mit IPS Panel',
      price: 399.99,
      purchasePrice: 299.99,
      stock: 8,
      minStock: 5,
      category: 'Elektronik',
      subcategory: 'Monitore',
      status: 'available',
      taxRate: 19,
      unit: 'Stück',
      isDigital: false,
      createdAt: new Date('2024-01-20'),
      tags: ['4K', 'IPS'],
    },
    {
      id: '5',
      articleNumber: 'ART-005',
      name: 'Mechanische Tastatur',
      description: 'RGB Gaming Tastatur mit Cherry MX Switches',
      price: 89.99,
      purchasePrice: 45.99,
      stock: 15,
      minStock: 10,
      category: 'Zubehör',
      subcategory: 'Eingabegeräte',
      status: 'available',
      taxRate: 19,
      unit: 'Stück',
      isDigital: false,
      createdAt: new Date('2024-03-01'),
      tags: ['Gaming', 'RGB', 'Mechanisch'],
    },
    {
      id: '6',
      articleNumber: 'ART-006',
      name: 'Webcam HD 1080p',
      description: 'Full HD Webcam mit Autofokus',
      price: 69.99,
      purchasePrice: 35.99,
      stock: 3,
      minStock: 5,
      category: 'Elektronik',
      subcategory: 'Kameras',
      status: 'available',
      taxRate: 19,
      unit: 'Stück',
      isDigital: false,
      createdAt: new Date('2024-02-25'),
      tags: ['HD', 'Webcam'],
    },
    {
      id: '7',
      articleNumber: 'ART-007',
      name: 'Software Lizenz Pro',
      description: 'Jahres-Lizenz für Pro Software',
      price: 199.99,
      stock: 999,
      minStock: 0,
      category: 'Software',
      status: 'available',
      taxRate: 19,
      unit: 'Lizenz',
      isDigital: true,
      createdAt: new Date('2024-01-01'),
      tags: ['Software', 'Lizenz', 'Digital'],
    },
    {
      id: '8',
      articleNumber: 'ART-008',
      name: 'Laptop-Ständer',
      description: 'Ergonomischer Aluminium Laptop-Ständer',
      price: 39.99,
      purchasePrice: 18.99,
      stock: 0,
      minStock: 10,
      category: 'Zubehör',
      subcategory: 'Ständer',
      status: 'unavailable',
      taxRate: 19,
      unit: 'Stück',
      isDigital: false,
      createdAt: new Date('2024-03-10'),
      tags: ['Ergonomisch', 'Aluminium'],
    },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Artikel</h1>
        <p className="mt-2 text-gray-600">Übersicht aller verfügbaren Artikel</p>
      </div>

      <ArticleList articles={articles} />
    </div>
  );
}
